### ISSUE TITLE
Place photo missing on the plan detail page

### ISSUE THREAD

**Issue by rwangsc18** [timwangmusic/Vacation-Planner#310]
![Screenshot 2023-09-07 at 10 24 16 PM](https://github.com/timwangmusic/Vacation-Planner/assets/54508739/66715085-b703-4f2e-8b1f-23886b35b7d8)

figure out the reason why a few places may have broken photo on the plan detail page.

**Comment by timwangmusic** [comment]
Can we consider pre-fetch the photos and if none of the photos is available we do not include the place at all?
